spring:
  application:
    name: TPO04Blog
  datasource:
    url: jdbc:h2:file:./src/main/resources/data/mydb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: false
  sql:
    init:
      mode: never
logging:
  level:
    org.hibernate.SQL: off
    org.hibernate.type.descriptor.sql.BasicBinder: off